# Generated by Django 3.1.7 on 2021-03-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_entry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stud_rec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
    ]
